name: seaseer
favicon: null
layout_spectrum: 0.3158676808234304
typography_spectrum: 0.66108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b4e85'
    - '#161d47'
    - '#9189a2'
    - '#b3abc2'
    - '#f0eced'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
